// Japanese and Spanish translations for Review System
// This file will be inserted into i18n.js

const jaTranslations = {
  // Auth
  'login': 'ログイン',
  'register': '登録',
  'logout': 'ログアウト',
  'email': 'メール',
  'password': 'パスワード',
  'username': 'ユーザー名',
  'confirmPassword': 'パスワード確認',
  'forgotPassword': 'パスワードを忘れた？',
  'resetPassword': 'パスワードリセット',
  'changePassword': 'パスワード変更',
  'currentPassword': '現在のパスワード',
  'newPassword': '新しいパスワード',
  'confirmNewPassword': '新しいパスワード確認',
  'passwordChanged': 'パスワード変更成功',
  'passwordReset': 'パスワードリセット成功',
  'requestPasswordReset': 'パスワードリセットをリクエスト',
  'sendResetLink': 'リセットリンク送信',
  'resetLinkSent': 'リセットリンク送信済み',
  'checkEmailForReset': 'メールアドレスが登録されている場合、パスワードリセットリンクが送信されます',
  'enterEmail': '登録したメールアドレスを入力してください',
  'resetTokenInvalid': 'リセットリンクは無効または期限切れです',
  'resetTokenExpired': 'リセットリンクの期限が切れました。新しいものをリクエストしてください',
  'backToLogin': 'ログインに戻る',
  'setNewPassword': '新しいパスワードを設定',
  'noAccount': 'アカウントをお持ちでないですか？',
  'haveAccount': '既にアカウントをお持ちですか？',
  'clickRegister': '登録する',
  'clickLogin': 'ログインする',
  'continueWithGoogle': 'Googleでログイン',
  'orDivider': 'または',
  'createUser': 'ユーザー作成',
  'addUser': 'ユーザー追加',
  
  // Navigation
  'dashboard': 'ダッシュボード',
  'myReviews': 'マイレビュー',
  'publicReviews': '公開レビュー',
  'publicReviewsManagement': '公開レビュー管理',
  'noPublicReviews': '公開レビューはまだありません',
  'confirmDeleteReview': 'このレビューを削除してもよろしいですか？この操作は元に戻せません。',
  'teams': 'チーム',
  'admin': '管理',
  'profile': 'プロフィール',
  
  // Review
  'createReview': 'レビュー作成',
  'reviewTitle': 'レビュータイトル',
  'reviewDescription': 'レビュー説明',
  'reviewDescriptionPlaceholder': 'このレビューの背景、目的、または注意事項を簡単に説明してください...',
  'template': 'テンプレート',
  'selectTemplate': 'テンプレート選択',
  'templateName': 'テンプレート名',
  'templateDescription': 'テンプレート説明',
  'templateCannotChange': 'テンプレートは作成後に変更できません',
  'defaultTemplate': 'デフォルトテンプレート',
  'personalReview': '個人レビュー',
  'teamReview': 'チームレビュー',
  'selectTeam': 'チーム選択',
  'pleaseSelectTeam': 'チームを選択してください',
  'status': 'ステータス',
  'draft': '下書き',
  'completed': '完了',
  'createdAt': '作成日',
  'updatedAt': '更新日',
  'creator': '作成者',
  'team': 'チーム',
  'actions': 'アクション',
  'edit': '編集',
  'delete': '削除',
  'view': '表示',
  'print': '印刷',
  'save': '保存',
  'cancel': 'キャンセル',
  'search': '検索',
  'back': '戻る',
  'next': '次へ',
  'previous': '前へ',
  'step': 'ステップ',
  'all': 'すべて',
  'yes': 'はい',
  'no': 'いいえ',
  
  // Messages
  'loginSuccess': 'ログイン成功',
  'loginFailed': 'ログイン失敗',
  'registerSuccess': '登録成功！アカウントでログインしてください',
  'registerSuccessShort': '登録成功',
  'registerFailed': '登録失敗',
  'passwordMismatch': 'パスワードが一致しません',
  'passwordTooShort': 'パスワードは6文字以上である必要があります',
  'fillAllFields': 'すべてのフィールドを入力してください',
  'createSuccess': '作成成功',
  'updateSuccess': '更新成功',
  'deleteSuccess': '削除成功',
  'operationFailed': '操作失敗',
  'confirmDelete': '削除してもよろしいですか？',
  'loading': '読み込み中...',
  'noData': 'データなし',
  
  // System
  'systemTitle': 'レビューシステムプラットフォーム',
  'systemSubtitle': '個人やチームの深いレビューをサポートし、継続的な改善を実現',
  'language': '言語',
  'switchLanguage': '言語切替',
  
  // User Settings
  'userSettings': 'ユーザー設定',
  'accountSettings': 'アカウント設定',
  'languagePreference': '言語設定',
  'saveChanges': '変更を保存',
  'settingsUpdated': '設定更新成功',
  'chinese': '中文',
  'english': 'English',
  'japanese': '日本語',
  'spanish': 'Español',
  'selectLanguage': '言語を選択',
  
  // Common
  'active': 'アクティブ',
  'inactive': '非アクティブ',
  'role': '役割',
  'userRole': 'ユーザー',
  'premiumRole': 'プレミアム',
  'adminRole': '管理者',
};

const esTranslations = {
  // Auth
  'login': 'Iniciar sesión',
  'register': 'Registrarse',
  'logout': 'Cerrar sesión',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'username': 'Nombre de usuario',
  'confirmPassword': 'Confirmar contraseña',
  'forgotPassword': '¿Olvidaste tu contraseña?',
  'resetPassword': 'Restablecer contraseña',
  'changePassword': 'Cambiar contraseña',
  'currentPassword': 'Contraseña actual',
  'newPassword': 'Nueva contraseña',
  'confirmNewPassword': 'Confirmar nueva contraseña',
  'passwordChanged': 'Contraseña cambiada exitosamente',
  'passwordReset': 'Contraseña restablecida exitosamente',
  'requestPasswordReset': 'Solicitar restablecimiento de contraseña',
  'sendResetLink': 'Enviar enlace de restablecimiento',
  'resetLinkSent': 'Enlace de restablecimiento enviado',
  'checkEmailForReset': 'Si tu correo está registrado, recibirás un enlace para restablecer tu contraseña',
  'enterEmail': 'Ingresa tu correo electrónico registrado',
  'resetTokenInvalid': 'El enlace de restablecimiento es inválido o ha expirado',
  'resetTokenExpired': 'El enlace de restablecimiento ha expirado, por favor solicita uno nuevo',
  'backToLogin': 'Volver al inicio de sesión',
  'setNewPassword': 'Establecer nueva contraseña',
  'noAccount': '¿No tienes una cuenta?',
  'haveAccount': '¿Ya tienes una cuenta?',
  'clickRegister': 'Haz clic para registrarte',
  'clickLogin': 'Haz clic para iniciar sesión',
  'continueWithGoogle': 'Continuar con Google',
  'orDivider': 'O',
  'createUser': 'Crear usuario',
  'addUser': 'Agregar usuario',
  
  // Navigation
  'dashboard': 'Panel de control',
  'myReviews': 'Mis revisiones',
  'publicReviews': 'Revisiones públicas',
  'publicReviewsManagement': 'Gestión de revisiones públicas',
  'noPublicReviews': 'Aún no hay revisiones públicas',
  'confirmDeleteReview': '¿Estás seguro de que deseas eliminar esta revisión? Esta acción no se puede deshacer.',
  'teams': 'Equipos',
  'admin': 'Administración',
  'profile': 'Perfil',
  
  // Review
  'createReview': 'Crear revisión',
  'reviewTitle': 'Título de la revisión',
  'reviewDescription': 'Descripción de la revisión',
  'reviewDescriptionPlaceholder': 'Por favor, describe brevemente el contexto, propósito o notas para esta revisión...',
  'template': 'Plantilla',
  'selectTemplate': 'Seleccionar plantilla',
  'templateName': 'Nombre de la plantilla',
  'templateDescription': 'Descripción de la plantilla',
  'templateCannotChange': 'La plantilla no se puede cambiar después de la creación',
  'defaultTemplate': 'Plantilla predeterminada',
  'personalReview': 'Revisión personal',
  'teamReview': 'Revisión de equipo',
  'selectTeam': 'Seleccionar equipo',
  'pleaseSelectTeam': 'Por favor selecciona un equipo',
  'status': 'Estado',
  'draft': 'Borrador',
  'completed': 'Completado',
  'createdAt': 'Creado en',
  'updatedAt': 'Actualizado en',
  'creator': 'Creador',
  'team': 'Equipo',
  'actions': 'Acciones',
  'edit': 'Editar',
  'delete': 'Eliminar',
  'view': 'Ver',
  'print': 'Imprimir',
  'save': 'Guardar',
  'cancel': 'Cancelar',
  'search': 'Buscar',
  'back': 'Atrás',
  'next': 'Siguiente',
  'previous': 'Anterior',
  'step': 'Paso',
  'all': 'Todos',
  'yes': 'Sí',
  'no': 'No',
  
  // Messages
  'loginSuccess': 'Inicio de sesión exitoso',
  'loginFailed': 'Inicio de sesión fallido',
  'registerSuccess': '¡Registro exitoso! Por favor inicia sesión con tu cuenta',
  'registerSuccessShort': 'Registro exitoso',
  'registerFailed': 'Registro fallido',
  'passwordMismatch': 'Las contraseñas no coinciden',
  'passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
  'fillAllFields': 'Por favor completa todos los campos',
  'createSuccess': 'Creado exitosamente',
  'updateSuccess': 'Actualizado exitosamente',
  'deleteSuccess': 'Eliminado exitosamente',
  'operationFailed': 'Operación fallida',
  'confirmDelete': '¿Confirmar eliminación?',
  'loading': 'Cargando...',
  'noData': 'Sin datos',
  
  // System
  'systemTitle': 'Plataforma del Sistema de Revisión',
  'systemSubtitle': 'Ayuda a individuos y equipos a realizar revisiones profundas para una mejora continua',
  'language': 'Idioma',
  'switchLanguage': 'Cambiar idioma',
  
  // User Settings
  'userSettings': 'Configuración de usuario',
  'accountSettings': 'Configuración de cuenta',
  'languagePreference': 'Preferencia de idioma',
  'saveChanges': 'Guardar cambios',
  'settingsUpdated': 'Configuración actualizada exitosamente',
  'chinese': '中文',
  'english': 'English',
  'japanese': '日本語',
  'spanish': 'Español',
  'selectLanguage': 'Seleccionar idioma',
  
  // Common
  'active': 'Activo',
  'inactive': 'Inactivo',
  'role': 'Rol',
  'userRole': 'Usuario',
  'premiumRole': 'Premium',
  'adminRole': 'Administrador',
};

console.log('Japanese translations:', Object.keys(jaTranslations).length);
console.log('Spanish translations:', Object.keys(esTranslations).length);
